export const cardList = [
  {
    id: 1,
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "БЕЗ СТАТУСА",
  },
  {
    id: 2,
    topic: "Research",
    title: "Новая задача",
    date: "31.10.23",
    status: "БЕЗ СТАТУСА",
  },
  {
    id: 3,
    topic: "Copywriting",
    title: "Задача по копирайтингу",
    date: "01.11.23",
    status: "НУЖНО СДЕЛАТЬ",
  },
  {
    id: 4,
    topic: "Web Design",
    title: "Дизайн лендинга",
    date: "02.11.23",
    status: "В РАБОТЕ",
  },
  {
    id: 5,
    topic: "Research",
    title: "Исследование рынка",
    date: "03.11.23",
    status: "В РАБОТЕ",
  },
  {
    id: 6,
    topic: "Copywriting",
    title: "Написание текстов",
    date: "04.11.23",
    status: "ТЕСТИРОВАНИЕ",
  },
  {
    id: 7,
    topic: "Web Design",
    title: "Адаптивная верстка",
    date: "05.11.23",
    status: "ГОТОВО",
  },
  {
    id: 8,
    topic: "Research",
    title: "Анализ конкурентов",
    date: "06.11.23",
    status: "БЕЗ СТАТУСА",
  },
  {
    id: 9,
    topic: "Copywriting",
    title: "SEO тексты",
    date: "07.11.23",
    status: "НУЖНО СДЕЛАТЬ",
  },
  {
    id: 10,
    topic: "Web Design",
    title: "UI/UX дизайн",
    date: "08.11.23",
    status: "В РАБОТЕ",
  },
];
